# Generated by Django 5.0.6 on 2024-07-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysqlapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentdetailsmodels',
            table='students',
        ),
    ]
